# Generated by Django 4.2.30 on 2026-05-26 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('manager', models.CharField(blank=True, max_length=50, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='شماره موبایل باید ۱۱ رقمی و با ۰۹ شروع شود')], verbose_name='شماره موبایل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('role', models.CharField(choices=[('operator', 'اپراتور'), ('technician', 'سرویس\u200cکار'), ('driver', 'راننده امداد')], max_length=20, verbose_name='نقش')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('category', models.CharField(choices=[('roadside', 'امدادی'), ('onsite', 'حضوری')], max_length=10, verbose_name='دسته\u200cبندی')),
                ('default_duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان پیش\u200cفرض')),
                ('base_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت پایه (تومان)')),
            ],
            options={
                'verbose_name': 'نوع خدمت',
                'verbose_name_plural': 'انواع خدمت',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پلاک')),
                ('plate_type', models.CharField(choices=[('personal', 'شخصی'), ('public', 'عمومی'), ('gov', 'دولتی'), ('taxi', 'تاکسی')], default='personal', max_length=10, verbose_name='نوع پلاک')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('model', models.CharField(max_length=50, verbose_name='مدل')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال ساخت')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='رنگ')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='شماره شاسی')),
                ('engine_number', models.CharField(blank=True, max_length=20, verbose_name='شماره موتور')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.customer', verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_source', models.CharField(choices=[('phone', 'تماس تلفنی'), ('onsite', 'مراجعه حضوری')], max_length=6, verbose_name='منبع درخواست')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('address', models.TextField(blank=True, verbose_name='آدرس یا توضیحات مکانی')),
                ('description', models.TextField(verbose_name='شرح خرابی/مشکل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('done', 'پایان\u200cیافته'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='نیروی اعزامی')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='شعبه')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='core.customer', verbose_name='مشتری')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='core.vehicle', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'درخواست خدمت',
                'verbose_name_plural': 'درخواست\u200cهای خدمت',
                'ordering': ['-request_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='شروع کار')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='پایان کار')),
                ('parts_used', models.TextField(blank=True, verbose_name='قطعات مصرفی')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه نهایی (تومان)')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='بازخورد مشتری')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='انجام\u200cدهنده')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.servicerequest', verbose_name='درخواست')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicetype', verbose_name='نوع خدمت')),
            ],
            options={
                'verbose_name': 'جزئیات خدمت',
                'verbose_name_plural': 'جزئیات خدمت',
            },
        ),
    ]
