# Generated by Django 4.2.30 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_id_alter_customer_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='full_plate',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='پلاک کامل'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_city_code',
            field=models.CharField(default='00', max_length=2, verbose_name='کد شهر'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_first_two',
            field=models.CharField(default='00', max_length=2, verbose_name='دو عدد اول'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_last_three',
            field=models.CharField(default='000', max_length=3, verbose_name='سه عدد آخر'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_letter',
            field=models.CharField(default='A', max_length=1, verbose_name='حرف'),
        ),
    ]
